services:
  tapestry-frontend:
    build: .
    image: tapestry-frontend
    container_name: tapestry-frontend
    ports:
      - "${PORT:-5173}:80"
    networks:
      - tapestry-net

networks:
  tapestry-net:

