import { Box, Typography, Divider, List, ListItem, Link } from "@mui/material";

function Section({ title, children, mt = 6 }) {
  return (
    <Box sx={{ mt }}>
      <Typography variant="h4" sx={{ fontWeight: 800, mb: 2 }}>
        {title}
      </Typography>
      {children}
    </Box>
  );
}

function Stat({ children }) {
  return (
    <ListItem sx={{ display: "list-item", py: 0.5, pl: 0 }}>
      <Typography variant="body2">{children}</Typography>
    </ListItem>
  );
}

export default function About() {
  return (
    <Box sx={{ maxWidth: 900 }}>
      <Typography variant="h3" color="primary" sx={{ fontWeight: 800, mb: 1 }}>
        About
      </Typography>
      <Typography color="text.secondary">
        Where TAPESTRY&apos;s data comes from, and how it&apos;s put
        together.
      </Typography>

      <Divider sx={{ my: 4 }} />

      <Section title="Where the data comes from" mt={0}>
        <Typography sx={{ mb: 2 }}>
          TAPESTRY is built on RNA-seq from the Kids First Pediatric Brain
          Tumor Atlas (PBTA), with clinical annotations and expression
          context pulled in through the OpenPedCan harmonization project.
          Splice junctions are called from that RNA-seq with rMATS, then
          compared against several normal-tissue reference cohorts to work
          out which junctions are tumor-enriched and which of those look
          oncofetal.
        </Typography>
        <Typography sx={{ mb: 2 }}>By the numbers, right now:</Typography>
        <List sx={{ listStyleType: "disc", pl: 4, py: 0 }}>
          <Stat>
            1,976 PBTA tumor RNA-seq specimens across 18 histologies,
            including 82 patient-derived cell lines (from CBTN).
          </Stat>
          <Stat>
            1,285 of those are independent primary tumors — the set used to
            call which junctions recur within a histology.
          </Stat>
          <Stat>
            10,676 recurrent tumor-enriched junctions (TEJs): 8,176
            tumor-specific and 2,500 oncofetal (about 23%).
          </Stat>
          <Stat>
            241 normal/control RNA-seq samples across four reference
            cohorts: 113 GTEx adult brain (under 40), 106 Evo-devo
            developmental brain (fetal through young adult), 7 pediatric
            normal brain, and 15 pediatric brain cell types.
          </Stat>
        </List>
      </Section>

      <Section title="Who's behind it">
        <Typography sx={{ mb: 2 }}>
          TAPESTRY comes out of the{" "}
          <Link
            href="https://rokitalab.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Rokita Lab
          </Link>
          , led by Dr. Jo Lynne Rokita, within the Brain Tumor Institute and
          Center for
          Cancer and Immunology Research at Children&apos;s National
          Hospital, and the Department of Pediatrics at the George
          Washington University School of Medicine and Health Sciences.
          The lab studies the genetic and molecular drivers of pediatric
          brain tumors — with a particular focus on how alternative
          splicing generates tumor-specific targets — and builds
          open-source tools and data resources, including OpenPBTA and
          OpenPedCan, which TAPESTRY&apos;s own data pipeline draws on, to
          make that work reusable across the field.
        </Typography>
        <Typography sx={{ mb: 2 }}>
          TAPESTRY itself was developed by{" "}
          <Link
            href="https://rokitalab.com/labmembers/03-patricia-sullivan.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Dr. Patricia Sullivan
          </Link>
          , with the underlying tumor-enriched junction data generated by{" "}
          <Link
            href="https://rokitalab.com/labmembers/02-ryan-corbett.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Dr. Ryan Corbett
          </Link>
          , and infrastructure support from{" "}
          <Link
            href="https://rokitalab.com/labmembers/10-chao-di.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Dr. Chao Di
          </Link>
          .
        </Typography>
      </Section>
    </Box>
  );
}
